/**
 * Shown once an Approver has written a rejection reason and is about to submit it —
 * lets them pick exactly who gets notified: the document's generator plus up to 2
 * Admins, or just the one Admin if the document was generated by an admin in the
 * first place (see signatureController.getRejectionCandidates, the single source of
 * truth this list is fetched from — the same rule is re-checked server-side, so
 * nothing selected here is ever trusted blindly).
 *
 * Used by both the logged-in Approver flow (ApprovalsPage) and the no-login
 * one-time email review link (ReviewDocumentPage) — same component, same rule.
 */
export default function RejectRecipientsPicker({ candidates, loading, selectedIds, onChange }) {
  const toggle = (id) => {
    if (selectedIds.includes(id)) {
      onChange(selectedIds.filter((x) => x !== id));
    } else {
      onChange([...selectedIds, id]);
    }
  };

  return (
    <div className="form-field" style={{ marginTop: 4 }}>
      <label>Send this rejection to</label>
      <p style={{ margin: '0 0 8px', fontSize: '0.82rem', color: '#64748B' }}>
        Choose who should be notified and can fix and resubmit this document.
      </p>

      {loading ? (
        <p style={{ fontSize: '0.85rem', color: '#64748B' }}>Loading recipients…</p>
      ) : candidates.length === 0 ? (
        <p className="modal-error">Couldn't determine who to notify for this document.</p>
      ) : (
        <div
          style={{
            display: 'flex', flexDirection: 'column', gap: 8,
            border: '1px solid #E2E8F0', borderRadius: 8, padding: '10px 12px',
          }}
        >
          {candidates.map((c) => (
            <label
              key={c.id}
              style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.9rem', cursor: 'pointer' }}
            >
              <input
                type="checkbox"
                checked={selectedIds.includes(c.id)}
                onChange={() => toggle(c.id)}
              />
              <span>{c.name}</span>
              <span
                style={{
                  fontSize: '0.72rem', padding: '1px 8px', borderRadius: 999,
                  background: c.isGenerator ? '#EFF6FF' : '#F8FAFC',
                  color: c.isGenerator ? '#1D4ED8' : '#0F172A',
                }}
              >
                {c.isGenerator ? 'Generator' : 'Admin'}
              </span>
            </label>
          ))}
        </div>
      )}
    </div>
  );
}
